
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane2 Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "67c72b4d-b694-4b92-b56a-1ccfc53d486a"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_to": "0efcef7c-dfb2-417c-af31-e0a57f76d4fb",
    "account_id_from": "74668697-41af-420f-a7b4-532bdf1c4759",
    "amount": 100
}