
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John3 Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "9f0413c0-07bb-4cc4-bc46-7f39eea193d7"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_to": "b362d2ee-25f1-49eb-92f1-83282eb1b34e",
    "account_id_from": "c2e90f8c-c9b7-4384-82ef-dc20945510f8",
    "amount": 100
}